### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by SilverFire** [Eomerx/less-space#1]
Hello. Could, you, please, tag current stable version and publish a release on GitHub?

**Comment by Eomerx** [comment]
Hi there.
Actually, i havent created new branches or tagged new versions while updating repo.
So, master branch is the latest stable and working one.
I'll keep in mind that on next releases and updates.

**Comment by SilverFire** [comment]
Sorry, I didn't explain the reasons of my request.
There is a [composer-asset-plugin](https://github.com/francoispluchino/composer-asset-plugin), which is frequently used in PHP world and gives us a way to load bower or npm packages using only composer (we write `composer require "bower-asset/less-space:*"` and that's all :smiley:)

Long story short, the plugin depends on GitHub releases and tags to fetch the required version of the dependency.
So I'll be very thankful it you could release.

**Comment by Eomerx** [comment]
Ok then.
I published a new release tagged with "1.1" version.

**Comment by SilverFire** [comment]
Thank you very much! :star2:

**Comment by SilverFire** [comment]
Seems, you forgot to change version in [bower.json](https://github.com/Eomerx/less-space/blob/master/bower.json) and [package.json](https://github.com/Eomerx/less-space/blob/master/package.json) before tagging :fearful:

The only way to fix it - release a `1.1.1` (don't forget to put 1.1.1 in those files before tagging) :)

**Comment by Eomerx** [comment]
oops. I forgot that.
Fixed.

**Comment by SilverFire** [comment]
Thank you!
